---
title: Dog Bites NYC
author: gregory_ut
date: '2022-01-09'
slug: []
categories:
  - R
tags:
  - R Markdown
  - map
  - plot
  - ggplot2
---


## Load packages and data
```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.show = "static")
library(tidyverse)
library(RSocrata)
library(tigris)
library(sf)
library(here)
library(tmap)
library(rgdal)
library(gt)

```


### you can get the data from here <https://data.cityofnewyork.us/Health/DOHMH-Dog-Bite-Data/rsgh-akpg>

```{r}
dog_bite_raw <- 
  read.socrata("https://data.cityofnewyork.us/resource/rsgh-akpg.csv") %>%
  tibble() %>%
  filter(borough %in% c("Brooklyn", "Manhattan", "Queens", "Bronx", "Staten Island"))

glimpse(dog_bite_raw)
```


## Count how many dog bites in each borough & plots
```{r}
# how many borrough occurances are there?
dog_bite_raw %>%
  count(borough)

# count NA's by column
dog_bite_raw %>%
  map_df(~sum(is.na(.)))



## need to find good ReGeX expressions to group by....
dog_bite <- dog_bite_raw %>%
  filter(!age %in% c("Y RS", "3Q", "")) %>%
  filter(!str_detect(age, "2018-0|2022"),
         age != "") %>%
  mutate(
    breed = case_when(
      breed == "American Pit Bull Terrier/Pit Bull" ~ "Pit Bull",
      breed == "American Pit Bull Mix / Pit Bull Mix" ~ "Pit Bull",
      TRUE ~ breed
    ),
    age_bin = case_when(
      str_detect(age, regex("^1$|MONS$|^[1-9]M$|MTHS|MOS|MTH", ignore_case = TRUE)) ~ "younging",
      str_detect(age, regex("^[1-5]$|^[1-5]Y$|^[1-5] YRS", ignore_case = TRUE)) ~ "mid - young",
      str_detect(age, regex("^[6-9]|^[6-9]\\sY$|^[6-9]", ignore_case = TRUE)) ~ "older - mature",
      str_detect(age, regex("\\d{2}(.*){3}$", ignore_case = TRUE)) ~ "Old :(",
      TRUE ~ "ERROR"
    )
  )  %>%
  filter(age_bin != "ERROR")



dog_bite %>% count(age_bin)




dog_bite %>%
  count(age_bin) %>%
  arrange(desc(n)) %>%
  filter(age_bin != "ERROR") %>%
  ggplot(aes(fct_reorder(age_bin, n), n, fill = age_bin)) +
  geom_col() +
  labs(title = "Age Group Bites.",
       x = "Age Bin",
       y = NULL) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 17))
  

dog_bite %>%
  group_by(breed, gender) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  filter(
    breed != "",
    breed %in% c(
      "Yorkshire Terrier",
      "UNKNOWN",
      "Shih Tzu",
      "Rottweiler",
      "Pit Bull",
      "Mixed/Other",
      "Maltese",
      "Labrador Retriever",
      "German Shepherd",
      "Chihuahua",
      "Bull dog"
    )
  ) %>%
  ggplot(aes(breed, count, fill = gender)) +
  geom_bar(position = "dodge", stat = "identity") +
  theme_minimal() +
  scale_fill_viridis_d(option = "C") +
  labs(title = "Dog Bites by Breed and Gender.") +
  theme(
    plot.title = element_text(
      hjust = 0.5,
      size = 16,
      face = "bold",
      family = "sans"
    ),
    axis.text.x = element_text(
      angle = 30,
      vjust = .8,
      hjust = 0.5
    )
  )


dog_bite %>%
  group_by(age) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  filter(age != "",
         n > 50) %>%
  gt() 




dog_bite_raw %>%
  filter(age != "") %>%
  group_by(age) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  head(10) %>%
  ggplot(aes(fct_reorder(age,-n), n)) +
  geom_col() +
  theme_minimal() +
  labs(title = "Top 10 biters by age.",
       x = "Age",
       y = "Count #") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 16))
```


## Get zip-code data
```{r, warning=FALSE, message=FALSE, ech}
# get nyc spatial boundaries zip codes
ny <- tigris::zctas(year = 2010, state = "NY")

# filter for zipcodes in dog bite dataframe
nyc <- ny %>%
  filter(ZCTA5CE10 %in% dog_bite_raw$zipcode) %>%
  select(ZCTA5CE10)

```

## Quick plot
```{r}

nyc <- janitor::clean_names(nyc)

head(dog_bite_raw)   
head(nyc)

# bar plot
dog_bite_raw %>%
  group_by(borough) %>%
  summarise(n = n()) %>%
  ggplot(aes(borough, n, fill = borough)) +
  geom_col() +
  scale_fill_viridis_d(option = "H") +
  labs(title = "Count of Dog Bites by borough.",
       fill = "Borough") +
  theme(
    panel.grid = element_blank(),
    panel.background = element_blank(),
    plot.title = element_text(size = 18, hjust = 0.5, face = 'bold', family = 'sans'),
    legend.box.background = element_rect(colour = "black", size = 2)
  )

```


## Join data together
```{r}
# join to spatial data
# count bites in each zipcode

dog_full <- nyc %>%
  rename(zipcode = zcta5ce10) %>%
  full_join(dog_bite_raw, by = ("zipcode")) %>%
  mutate(uniqueid = as.character(uniqueid)) %>%
  drop_na() %>%
  group_by(zipcode) %>% 
  summarise(bites = n())

```

## Create Maps
```{r, warning=FALSE}
dog_full %>%
  st_crop(c(xmin = -74.31436, ymin = 40.49593, xmax = -73.6, ymax = 41.0)) %>%
  ggplot(aes(fill = bites)) +
  geom_sf(lwd = 0.3) +
  scale_fill_viridis_c(option = "H") +
  labs(title = "Dog Bites in NYC.",
       caption = "Data: https://data.cityofnewyork.us/resource/rsgh-akpg.csv",
       fill = "# Bites") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 18, face = "bold"))

```


```{r}
# similar version map with tmap
dog_full %>%
  st_crop(c(
    xmin = -74.31436,
    ymin = 40.49593,
    xmax = -73.6,
    ymax = 41.0
  )) %>%
  tm_shape() +
  tm_fill("bites",
          style = "quantile",
          n = 5,
          title = "Dog bites") +
  tm_borders(col = "black",
             lwd = 0.3) +
  tm_layout(
    title = "Dog Bites in NYC.",
    legend.outside = TRUE,
    legend.outside.position = "left",
    title.fontface = "bold"
  )

```