---
title: Dog Bites NYC
author: gregory_ut
date: '2022-01-09'
slug: []
categories:
  - R
tags:
  - R Markdown
  - map
  - plot
  - ggplot2
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages and data
### you can get the data from here <https://data.cityofnewyork.us/Health/DOHMH-Dog-Bite-Data/rsgh-akpg>

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(RSocrata)
library(tidyverse)
library(tigris)
library(sf)
library(here)
library(tmap)


dog_bite_raw <- 
  read.socrata("https://data.cityofnewyork.us/resource/rsgh-akpg.csv") %>%
  as_tibble() %>%
  filter(borough %in% c("Brooklyn", "Manhattan", "Queens", "Bronx", "Staten Island"))
```


## Count how many dog bites in each borough.
```{r}
dog_bite_raw %>%
  count(borough)
```


## Get zip-code data
```{r}
# get nyc spatial boundaries zip codes
nyc <- tigris::zctas(year = 2010, state = "NY")

# filter for zipcodes in dog bite dataframe
nyc2 <- nyc %>%
  filter(ZCTA5CE10 %in% dog_bite_raw$zipcode)

```

## Quick plot
```{r}
nyc2 <- janitor::clean_names(nyc2)

head(dog_bite_raw)


dog_bite_raw %>%
  group_by(borough) %>%
  summarise(n = n()) %>%
  ggplot(aes(borough, n, fill = borough)) +
  geom_col() +
  theme_bw()


glimpse(nyc)
glimpse(dog_bite_raw)

```

## Join data together
```{r}
# join to spatial data
dog_full <- nyc2 %>%
  rename(zipcode = zcta5ce10) %>%
  full_join(dog_bite_raw, by = c("zipcode" = "zipcode"))

# convert to character
dog_full$uniqueid <- as.character(dog_full$uniqueid)

# summarise by zipcode
dogg <- dog_full %>%
  na.omit() %>%
  group_by(zipcode) %>%
  summarize(bites = n())

```

## Create Maps
```{r}
dogg %>%
  ggplot(aes(fill = bites)) +
  geom_sf(lwd = 0.3) +
  scale_fill_gradient2() +
  labs(title = "Dog Bites in New York City.",
       caption = "Data: https://data.cityofnewyork.us/resource/rsgh-akpg.csv",
       fill = "# Bites") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 18, face = "bold"))

# similar version map with tmap
tm_shape(dogg) +
  tm_fill("bites",
          style = "quantile",
          n = 5,
          title = "Dog bites") +
  tm_borders(col = "black",
             lwd = 0.3) +
  tm_layout(title = "Dog Bites in New York City.",
            legend.outside = TRUE,
            legend.outside.position = "left",
            title.fontface = "bold")

```