---
title: Kriging-IncomeNYC
author: gregory_ut
date: '2022-02-04'
slug: []
categories:
  - R
  - sf
  - dplyr
  - ggplot2
tags: []
---

### Load Packages
```{r, message=FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(gstat)
library(sp)
library(stars)
library(raster)
sf::sf_use_s2(FALSE)
theme_set(theme_minimal())
```


### Get median income data from Census and transform it to spatial points.
```{r, warning=FALSE, results='hide'}
inc <- get_acs(geography = "tract",
               variables = "B19013_001",
               state = "NY",
               county = c("New York", "Kings", "Richmond", "Queens", "Bronx"),
               geometry = TRUE)

```


```{r, warning=FALSE, message=FALSE}
inc %>%
  mutate(boro = case_when(str_detect(NAME, "Kings") ~ "Brooklyn",
                          str_detect(NAME, "New York County") ~ "Manhattan",
                          str_detect(NAME, "Bronx") ~ "Bronx",
                          str_detect(NAME, "Queens") ~ "Queens",
                          str_detect(NAME, "Richmond") ~ "Staten Island")) %>%
  ggplot(aes(estimate, color = boro)) +
  stat_ecdf(geom = "step") +
  scale_x_continuous(labels = scales::dollar) +
  labs(title = "Income CDF by Borough.") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = 'bold'))

```

### Create spatial points from multiplogon shp.
```{r, warning=FALSE}
# create spatial point df, with centroids as points.
inc_c <- inc %>%
  mutate(centr = st_centroid(.) %>%
           st_geometry(.)) %>%
  st_drop_geometry() %>%
  st_as_sf() %>%
  drop_na(estimate, moe) %>%
  cbind(st_coordinates(.)) %>%
  st_transform(32618)

## Plot points
inc_c %>%
  ggplot(aes(color = estimate, size = estimate)) +
  geom_sf(alpha = 0.6) +
  scale_color_gradient2() +
  labs(title = "Income Points.") +
  theme(plot.title = element_text(
    hjust = 0.5,
    size = 18,
    face = 'bold',
    family = "sans"),
  panel.grid = element_blank())

# Count NA values by column
map_chr(inc_c, ~sum(is.na(.)))

```




### Spatial analysis of clustering.
```{r}

# convert to sp format
inc_sp <- as(inc_c, "Spatial")

# variogram
inc_var <- gstat::variogram(estimate ~ 1, inc_sp)

ggplot(tibble(inc_var), aes(dist, np)) +
  geom_point(size = 4, color = "#A95DC2") +
  labs(title = "Variogram") +
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5,
                                  face = 'bold',
                                  size = 20))


# fit variogram
plot(automap::autofitVariogram(estimate~1, as(inc_c, "Spatial")))

```

### Prepare for Kriging 
```{r}
# create spatial grid for kriging
grid_inc <- inc_c %>%
  st_transform(32618) %>%
  st_make_grid(cellsize = c(100, 100), # 100m pixel size
               what = "centers") %>%
  st_as_sf() %>%
  cbind(., st_coordinates(.))

grid_inc <- as(grid_inc, "Spatial")
gridded(grid_inc) <- TRUE
grid_inc <- as(grid_inc, "SpatialPixels") # specifying what kind of grid
plot(grid_inc, col = 'grey')
```

### Universal Kriging
```{r}
# get variogram model statistics
var_mod <- automap::autofitVariogram(estimate ~ X + Y, inc_sp)$var_model
var_mod

# Kriging
UK <- krige(
  estimate ~ coords.x1 + coords.x2,
  inc_sp, 
  grid_inc,         
  model = var_mod
  )
```


### Prepare for plotting
```{r}
# create boundary to which to clip
bounds <- st_union(inc)


uk <- as.data.frame(UK)
names(uk)[1:3] <- c("coord_x", "coord_y", "prediction")


# erase water function
st_erase <- function(x, y) {
  st_difference(x, st_union(y))
}

# get water data
ny_water <-
  tigris::area_water("NY",
                     c("Bronx", "New York", "Kings", "Queens", "Richmond"),
                     class = "sf") 

inc <-  inc %>%
  st_transform(32618)


ggplot() +
  geom_tile(data = uk, aes(coord_x, coord_y, fill = prediction)) +
  geom_sf(data = inc, alpha = 0.0, lwd = 0.1, color = 'black')

```



### Convert Kriging results to raster
```{r}
ras <- raster(UK)

ras <- mask(ras, as(bounds %>% 
                      st_transform(32618),
                    "Spatial"))

plot(ras, main = "Median Income")

```

### Categorical Plot, 
```{r, message=FALSE, warning=FALSE}
# convert to to spatial points dataFrame
rasp <- rasterToPoints(ras)
rasp_df <- data.frame(rasp)


# covert to right CRS before spatial join
rasp_sf <- rasp_df %>% 
            st_as_sf(., coords = c("x", "y"), 
                     crs = st_crs(4269))

# spatial join to tracts shapefile
inc_df <- inc %>%
  st_transform(4269) %>%
  st_erase(ny_water) %>%
  st_join(rasp_sf %>% drop_na(.),
          join = st_within) %>%
  group_by(GEOID) %>%
  summarise(sum_var1 = sum(estimate))

# make income categories and plot
inc_df %>%
  mutate(
    cat_inc = factor(case_when(
      sum_var1 > 150000 ~ "151,000$ & Abv.",
      sum_var1 <= 150000 &
        sum_var1 > 95000 ~ "95,000$ to 150000$",
      sum_var1 < 95000 &
        sum_var1 > 70000 ~ "70,000$ to 95,000$",
      sum_var1 < 70000 & sum_var1 > 40000 ~ "Less than 70,000$",
      sum_var1 < 40000 ~ "Less than 40,000$",
      TRUE ~ NA_character_)
  ),
  cat_inc = fct_reorder(cat_inc, sum_var1)) %>% 
  ggplot(aes(fill = cat_inc)) +
  geom_sf(lwd = 0.2) +
  scale_fill_manual(values = c("#ffee99", "#d4d94c", "#77b46c", "#3d8799", "#2b57d9")) +
  theme(panel.grid = element_blank())
```
